<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class PrincipleController extends Controller
{
    public function show(string $principle): View
    {
        $principles = [
            'transparency' => [
                'title' => 'Principle of Transparency',
                'description' => 'Transparency supports effective human oversight and intervention. People should have access to relevant information about how the AI model works and which limitations affect its outputs.',
                'example' => 'An AI-assisted decision interface can disclose that a recommendation was generated by a model, present the most influential factors and provide further technical information on demand.',
            ],
            'fairness' => [
                'title' => 'Principle of Fairness',
                'description' => 'Fairness reflects equality and inclusiveness. The design of an AI system should consider different people and contexts, reducing biased or discriminatory outcomes.',
                'example' => 'A screening tool can expose the criteria used for ranking, monitor differences between demographic groups and provide a human review channel for contested outcomes.',
            ],
            'automation-level' => [
                'title' => 'Principle of Automation Level',
                'description' => 'The appropriate balance between automation and human control depends on context, risk and user needs. Interfaces should make the level of autonomy understandable and support meaningful intervention.',
                'example' => 'A clinical support system may generate recommendations automatically while leaving confirmation, correction and final responsibility to qualified professionals.',
            ],
            'protection' => [
                'title' => 'Principle of Protection',
                'description' => 'A human-centered AI system should protect safety, security and privacy throughout its lifecycle. Data collection and system behavior should be proportionate, resilient and understandable.',
                'example' => 'A conversational assistant can minimize collected data, clearly indicate what is stored and allow users to remove previous conversations or revoke consent.',
            ],
        ];

        abort_unless(isset($principles[$principle]), 404);

        return view('pages.principle', ['principle' => $principles[$principle]]);
    }
}
