<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class PrincipleController extends Controller
{
    public function show(string $principle): View
    {
        $principles = [
            'transparency' => [
                'title' => 'Principle of Transparency',
                'description' => 'Principle of Transparency supports effective human oversight and intervention. People should have access to relevant information about how the AI model works and which limitations affect its outputs. This principle ensures that AI systems are open and observable, guaranteeing that humans can understand the system\'s purpose, its decision-making processes, and the rationale behind its responses. By being transparent, an AI system builds trust, enables effective human oversight, and allows users to verify and challenge its decisions.',
                'example' => 'An AI-assisted decision interface can disclose that a recommendation was generated by a model, present the most influential factors and provide further technical information on demand.',
                'code' =>'P1',
            ],
            'fairness' => [
                'title' => 'Principle of Fairness',
                'description' => 'Principle of Fairness reflects equality and inclusiveness. The design of an AI system should consider different people and contexts, reducing biased or discriminatory outcomes. This principle ensures that AI systems operate without prejudice or discrimination, requiring that they be designed and trained to avoid amplifying societal biases, treat all individuals equitably, and provide accurate and reliable information. A fair AI system actively safeguards human rights and promotes inclusiveness.',
                'example' => 'A screening tool can expose the criteria used for ranking, monitor differences between demographic groups and provide a human review channel for contested outcomes.',
                'code' =>'P2',
            ],
            'automation-level' => [
                'title' => 'Principle of Automation Level',
                'description' => 'The appropriate balance between automation and human control depends on context, risk and user needs. Interfaces should make the level of autonomy understandable and support meaningful intervention. This principle defines the crucial balance between human control and machine autonomy, establishing that the level of automation must be appropriate for the task and context. By guaranteeing effective human oversight or active human participation, this principle prevents the system from becoming a black box and ensures that final decisions remain under human authority, particularly in high-stakes situations.',
                'example' => 'A clinical support system may generate recommendations automatically while leaving confirmation, correction and final responsibility to qualified professionals.',
                'code' =>'P3',
            ],
            'protection' => [
                'title' => 'Principle of Protection',
                'description' => 'Principle of Protection defines that a human-centered AI system should protect safety, security and privacy throughout its lifecycle. Data collection and system behavior should be proportionate, resilient and understandable. This principle emphasizes the need to safeguard users from any form of harm, encompassing the security of the system against external threats, the safety of its operation to prevent physical or psychological damage, and the privacy of the user\'s personal data. An AI system built on this principle is resilient, respects individual autonomy, and operates in a trustworthy and dependable manner.',
                'example' => 'A conversational assistant can minimize collected data, clearly indicate what is stored and allow users to remove previous conversations or revoke consent.',
                'code' =>'P4',
            ],
        ];

        abort_unless(isset($principles[$principle]), 404);

        return view('pages.principle', ['principle' => $principles[$principle]]);
    }
}
